version: "3.9"

services:
  api:
    image: ghcr.io/juanraniqueo/transformacion_digital:latest
    container_name: api-ci-cd
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: http://54.221.143.59:8000
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: api_cicd
      DB_USERNAME: api_user
      DB_PASSWORD: api_pass
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: api-ci-cd-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_cicd
      MYSQL_USER: api_user
      MYSQL_PASSWORD: api_pass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
