name: CD API Laravel

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo de Infraestructura
        uses: actions/checkout@v4

      - name: Configurar Python (para Ansible)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Configurar clave SSH para conectar a la VM
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          printf "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      - name: Ejecutar playbook de despliegue
        working-directory: ansible
        env:
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
        run: |
          ansible-playbook -i hosts.ini deploy.yml
